
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RBRACK = 28;
  public static final int TIMES = 16;
  public static final int AND = 22;
  public static final int NE = 19;
  public static final int LT = 10;
  public static final int ELSE = 3;
  public static final int TRUTH = 33;
  public static final int PLUS = 14;
  public static final int RPAREN = 26;
  public static final int OR = 21;
  public static final int INT = 6;
  public static final int LTE = 11;
  public static final int SEMI = 23;
  public static final int COMP = 18;
  public static final int WHILE = 4;
  public static final int LBRACK = 27;
  public static final int RETURN = 7;
  public static final int ERROR = 34;
  public static final int IDEN = 32;
  public static final int IF = 2;
  public static final int LPAREN = 25;
  public static final int GT = 12;
  public static final int GTE = 13;
  public static final int NUM = 31;
  public static final int LCB = 29;
  public static final int TILDA = 20;
  public static final int COMMA = 24;
  public static final int EOF = 0;
  public static final int DIVIDE = 17;
  public static final int MINUS = 15;
  public static final int error = 1;
  public static final int RCB = 30;
  public static final int EQ = 9;
  public static final int BOOL = 5;
  public static final int VOID = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "WHILE",
  "BOOL",
  "INT",
  "RETURN",
  "VOID",
  "EQ",
  "LT",
  "LTE",
  "GT",
  "GTE",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "COMP",
  "NE",
  "TILDA",
  "OR",
  "AND",
  "SEMI",
  "COMMA",
  "LPAREN",
  "RPAREN",
  "LBRACK",
  "RBRACK",
  "LCB",
  "RCB",
  "NUM",
  "IDEN",
  "TRUTH",
  "ERROR"
  };
}

